name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build the production artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Fetch package dependencies
        run: flutter pub get

      - name: Build the bundle
        run: |
          flutter build web --web-renderer canvaskit --release

      - uses: papeloto/action-zip@v1
        with:
          files: build/web/**
          dest: web-archive.zip

      - name: Archive itch.io artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web-archive
          path: web-archive.zip

  publish_itch:
    name: Publish apk to itch.io
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download archive from build
        uses: actions/download-artifact@v2
        with:
          name: web-archive

      - name: Publish to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: html
          ITCH_GAME: bugman
          ITCH_USER: fstof
          PACKAGE: "web-archive.zip"
