name: CI
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build the production artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter environment
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Get version numbers
        run: |
          BUILD=$GITHUB_RUN_NUMBER
          echo "BUILD=$BUILD" >> $GITHUB_ENV
          echo "BUILD=$BUILD" >> version.txt
          echo "build: $BUILD"

      - name: Fetch package dependencies
        run: flutter pub get

      - name: Build the bundle
        run: |
          flutter build web --web-renderer=canvaskit --base-href=/$GITHUB_RUN_NUMBER/ --release

      - name: Archive itch.io artifacts
        uses: actions/upload-artifact@v2
        with:
          name: web-archive
          path: build

      - name: Archive version file
        uses: actions/upload-artifact@v2
        with:
          name: version
          path: version.txt


  publish_itch:
    name: Publish to itch.io
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download archive from build
        uses: actions/download-artifact@v2
        with:
          name: web-archive

      - name: Download version file
        uses: actions/download-artifact@v2
        with:
          name: version

      - name: Load version number
        run: |
          source version.txt
          echo "BUILD=$BUILD" >> $GITHUB_ENV

      - name: Publish to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: html
          ITCH_GAME: bugman
          ITCH_USER: fstof
          PACKAGE: web
          VERSION: "${{ env.BUILD }}"